name: Building and pushing a docker image to Amazon ECR

on:
  push:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: us-west-2
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REPO_NAME: twitch-bot

jobs:
  build-and-push:
    name: Building and pushing image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag the image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: $REPO_NAME:treeemotes
          IMAGE_TAG: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:treeemotes
        run: |
          docker build . \
            --build-arg server_port=${{ secrets.TREE_BOT_SERVER_PORT }} --build-arg bot_client_id=${{ secrets.TREE_BOT_CLIENT_ID }} \
            --build-arg bot_client_secret=${{ secrets.TREE_BOT_CLIENT_SECRET }} --build-arg steam_api_key=${{ secrets.TREE_BOT_STEAM_API_KEY }} \
            --build-arg steam_user_id=${{ secrets.TREE_BOT_STEAM_USER_ID }} --build-arg irc_user=${{ secrets.TREE_BOT_IRC_USER }} \
            --build-arg irc_user_oauth_password=${{ secrets.TREE_BOT_IRC_OAUTH_PASSWORD }} --build-arg irc_channels_to_monitor=${{ secrets.TREE_BOT_IRC_CHANNELS_TO_MONITOR }} \
            --build-arg bot_publisher_secret=${{ secrets.BOT_PUBLISHER_SECRET }} \
            -t treeemotes \
            -t ${{ steps.login-ecr.outputs.registry }}/$REPO_NAME:treeemotes

      - name: Push
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$REPO_NAME:treeemotes
